### PR TITLE
mkbundle: fix 17139 mono aot register module fix definitions

### LINKED ISSUE #17139: mono_aot_register_module conflicting definitions
I work with a quite complex build system calling mkbundle with `--keep-temp`, manually patching the resulting C files (e.g. writing our own `main`) and then compiling the result with GCC 7.4.0. 

This whole process aims to allow us to link precisely and circumvent several problems (possible bugs) we encountered in mkbundle.

It's quite complicated to create a minimal setup reproducing this issue, the original script failing on mono 6.4 is here: https://github.com/renode/renode/blob/master/tools/packaging/make_linux_portable.sh

The problem I encounter when finally calling gcc:

```
/home/.../renode/tools/packaging/renode_1.8.0_portable-workdir/bundler.c:381:6: error: conflicting types for 'mono_aot_register_module'
 void mono_aot_register_module (void *aot_info);
      ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/.../renode/tools/packaging/renode_1.8.0_portable-workdir/bundler.c:5:0:
/usr/include/mono-2.0/mono/jit/jit.h:107:1: note: previous declaration of 'mono_aot_register_module' was here
 mono_aot_register_module (void **aot_info);
```

The `bundler.c` file is `temp.c` generated by mkbundle with our additions.

I do believe this was introduced with https://github.com/mono/mono/pull/15132 - before that we had to manually add a declaration for `mono_aot_register_module`.

I seems to me that a fix should be applied to `mcs/tools/mkbundle/template_common.inc`. There is this fragment:

```
#ifdef USE_DEFAULT_MONO_API_STRUCT
// We don't export in jit.h
// So declare here, and get it from mono
void mono_aot_register_module (void *aot_info);
#endif // USE_DEFAULT_MONO_API_STRUCT
```

The comment is clearly not relevant anymore and this code is pointed by the GCC error: bundler.c:381:6.

I will create a PR fixing this, but I am not 100% sure how to test it robustly, so please feel free to drop it if needed.

I believe the PR will just drop the quoted piece of code.

### PR DESCRIPTION
**Pull request by PiotrZierhoffer**
This change fixes conflicting definitions of mono_aot_register_module.

This caused our mkbundle use case to fail on mono 6.4.

Also removed a seemingly unneeded definition in template_common.inc.

Fixes #17139

### CODE REVIEW

**Comment by marek-safar** [comment]
approve

**Comment by PiotrZierhoffer** [comment]
I can see one of the tests failed with a crash. I tried to read the log, but I can't see anything relevant to my changes here. Copied it to a gist: https://gist.github.com/PiotrZierhoffer/ad168781c03c86d78d187af2642dc719

What should I do now?

**Comment by lewurm** [comment]
@monojenkins build Linux i386

**Comment by lewurm** [comment]
@PiotrZierhoffer unfortunately we have some flakiness in our CI setup. I triggered a re-run and it will likely be fine then. The crash doesn't look related to your change.

@lambdageek FYI, the crash was:
```
***** MonoTests.System.ExceptionTest.DumpICallTotalAsync
mono_coop_mutex_lock Cannot transition thread 0xf3effb40 from STATE_BLOCKING with DO_BLOCKING
```
