### ISSUE TITLE
[WASM] Missing WABT binaries after updating Emscripten to 1.39.18

### ISSUE THREAD

**Issue by davilovick** [mono/mono#20002]
Hi, @emepetres, @MarcosCobena and I are trying to create a OpenGL binding for mono wasm.
We have noticed that since the update of EMSDK version to 1.39.18 in #19980  there are a lot of missing executables in _mono\sdks\builds\toolchains\emsdk\upstream\bin folder_, in particular, it seems that all WABT binaries are missing. 

This causes a compilation failed after using packager.exe (I've attached a ninga.log file):
/bin/sh: 1: /home/davilovick/mono/sdks/builds/toolchains/emsdk/upstream/bin/wasm-strip: not found

## Steps to Reproduce

1. Clone and build mono git repo.
2. Go to mono\sdks\builds\toolchains\emsdk\upstream\bin folder
3. Check that wasm-strip file (for instance) is missing

This is a list with all files after #19980:
[BinariesAfter.txt](https://github.com/mono/mono/files/4814171/BinariesAfter.txt)

This is a list with all files before #19980:
[BinariesBefore.txt](https://github.com/mono/mono/files/4814172/BinariesBefore.txt)

Ninja.log after a failed build
[ninja.log](https://github.com/mono/mono/files/4814296/ninja.log)

### Current Behavior
WABT binaries are missing from mono\sdks\builds\toolchains\emsdk\upstream\bin

### Expected Behavior
WABT binaries found at mono\sdks\builds\toolchains\emsdk\upstream\bin

## On which platforms did you notice this

[ ] macOS
[X ] Linux
[ ] Windows

**Version Used**:
Mono master:
commit #2c2a1718a93addcdebd4fc8693fb6b0d6d44b917

**Comment by vargaz** [comment]
As a workaround, pass --no-native-strip to the packager.
