### ISSUE TITLE
Build fails on Redhat 6.8 with GCC 4.4.7

### ISSUE THREAD

**Issue by rjvdboon** [mono/mono#8572]
## Steps to Reproduce
On a machine with GCC 4.4.7 as the default compiler (i.e. stock Centos6.9)
1. clone mono master
2. configure
3. make

### Current Behavior

Build fails.

### Expected Behavior

Build completes.

## On which platforms did you notice this

[ ] macOS
[ X ] Linux
[ ] Windows

**Version Used**:

```
$ git branch -v
* master dbfbffb559a Bump API snapshot submodule
$ gcc --version | head -1
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-17)
$ uname -srv
Linux 2.6.32-696.3.2.el6.x86_64 #1 SMP Wed Jun 7 11:51:39 EDT 2017
```

## Stacktrace

```
trace.c: In function ‘mono_trace_enter_method’:
trace.c:146: error: #pragma GCC diagnostic not allowed inside functions
trace.c:148: error: #pragma GCC diagnostic not allowed inside functions
make[4]: *** [libmini_la-trace.lo] Error 1
make[4]: Leaving directory `/scratch/nlrvmp/mono/mono-git/mono/mini'
make[3]: *** [all] Error 2
make[3]: Leaving directory `/scratch/nlrvmp/mono/mono-git/mono/mini'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/scratch/nlrvmp/mono/mono-git/mono'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/scratch/nlrvmp/mono/mono-git'
make: *** [all] Error 2
```

Commenting out lines 146 and 148 gets me a successful build. I think this was introduced with #8308.

**Comment by directhex** [comment]
How much do we care about supporting GCC 4.4? It's already a no-go for BTLS, so we switched to using "Devtoolset" in package builds, to get a newer compiler

**Comment by luhenry** [comment]
If it's a no-go for BTLS, then I don't think we care about it very much. @directhex which Linux that we currently support would it stop us from supporting?

**Comment by directhex** [comment]
It shouldn't affect us. The packages which rely on a newer GCC (well, G++) we work around using devtoolset (which gives us GCC/G++ 4.8). I have to manually check we aren't adding dependencies on post-libstdc++-4.4 _methods_, but so far everything is clean.

**Comment by marek-safar** [comment]
BTLS is optional and the change was just small warning suppression fix. Let's make it compile again.

/cc @lewurm

**Comment by jaykrell** [comment]
Would be fixed by this:
https://github.com/mono/mono/pull/8579
