### ISSUE TITLE
Reference to type 'IAsyncDisposable' claims it is defined in 'mscorlib', but it could not be found

### ISSUE THREAD

**Issue by mikkeljohnsen** [mono/mono#17181]
## Steps to Reproduce

1. Make a cs file that uses IAsyncDisposable
2. Compile using "csc -nostdlib -langversion:7.3 -r:/usr/lib/mono/4.7.2-api/mscorlib.dll DB.cs" Fails.
3. But "csc DB.cs" works.

### Current Behavior

Mono 6.4 fails to compile if using mscorlib.dll from /usr/lib/mono/4.7.2-api/

### Expected Behavior

Should compile with no problem as mono 6.0 and before did.

## On which platforms did you notice this

[ ] macOS
[x ] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 6.4.0.198 (tarball Mon Sep 23 20:53:41 UTC 2019)

## Stacktrace

```
/usr/bin/csc -nologo -nowarn:CS0649,CS0169 -nostdlib -noconfig -langversion:7.3 -r:/usr/lib/mono/4.7.2-api/mscorlib.dll -r:/usr/lib/mono/4.7.2-api/Facades/netstandard.dll -r:/usr/lib/mono/4.7.2-api/System.dll  -define:NET_4_5 -define:LINUX_OS -define:X86_64 -define:DEBUG -define:TRACE -debug:pdbonly -define:WEBKIT -define:NPGSQL -define:CFG_GSETTINGS -define:DBUS_SYSTEM -out:xcare-dbgenerate.exe -resource:data.template -resource:datacollection.template -r:System.Core.dll -r:System.Data.dll `pkg-config --libs Npgsql` ./dbgenerate.cs AssemblyInfo.cs
dbgenerate.cs(229,12): error CS7069: Reference to type 'IAsyncDisposable' claims it is defined in 'mscorlib', but it could not be found
dbgenerate.cs(248,15): error CS7069: Reference to type 'IAsyncDisposable' claims it is defined in 'mscorlib', but it could not be found
dbgenerate.cs(337,16): error CS7069: Reference to type 'IAsyncDisposable' claims it is defined in 'mscorlib', but it could not be found
dbgenerate.cs(363,17): error CS7069: Reference to type 'IAsyncDisposable' claims it is defined in 'mscorlib', but it could not be found
dbgenerate.cs(367,18): error CS7069: Reference to type 'IAsyncDisposable' claims it is defined in 'mscorlib', but it could not be found
dbgenerate.cs(393,17): error CS7069: Reference to type 'IAsyncDisposable' claims it is defined in 'mscorlib', but it could not be found
dbgenerate.cs(397,18): error CS7069: Reference to type 'IAsyncDisposable' claims it is defined in 'mscorlib', but it could not be found
dbgenerate.cs(481,17): error CS7069: Reference to type 'IAsyncDisposable' claims it is defined in 'mscorlib', but it could not be found
dbgenerate.cs(2984,12): error CS7069: Reference to type 'IAsyncDisposable' claims it is defined in 'mscorlib', but it could not be found
dbgenerate.cs(2987,13): error CS7069: Reference to type 'IAsyncDisposable' claims it is defined in 'mscorlib', but it could not be found

```

**Comment by marek-safar** [comment]
This is interesting. Are you defining your own `IAsyncDisposable` (ideally attach your DB.cs)

**Comment by mikkeljohnsen** [comment]
No I’m just using Npgsql 4.0.10

**Comment by marek-safar** [comment]
Could you please attach your sample project?

**Comment by mikkeljohnsen** [comment]
This was my bad. I think the problem, was that i still some places also used "-r:System.Xml.dll" and it would load from default location and on 6.0.0 that was also 4.7.2. But with 6.4.0 the default place is 4.8.
So there was a mismatch.
