### PR TITLE
Fix compilation of AOT-less Mono

### PR DESCRIPTION
**Pull request by JustArchi**
```
aot-runtime.c:5838:1: error: expected identifier or ‘(’ before ‘{’ token
 {
 ^
```

### CODE REVIEW

**Comment by JustArchi** [comment]
CC @vargaz as it got broken in https://github.com/mono/mono/commit/b657c7b0e60f46a0e920cf165933efe120b6b479#diff-95eedb3ffaa1389a6073d73d65b22af9R5836
