### ISSUE TITLE
.NET Core build broken

### ISSUE THREAD

**Issue by directhex** [mono/mono#14263]
```
/home/vsts/work/1/s/netcore/System.Private.CoreLib/shared/System/Threading/ThreadPool.cs(1294,71): error CS0103: The name 'PendingUnmanagedWorkItemCount' does not exist in the current context [/home/vsts/work/1/s/mcs/class/System.Private.CoreLib/System.Private.CoreLib.csproj]
/home/vsts/work/1/s/netcore/System.Private.CoreLib/shared/System/Activator.RuntimeType.cs(124,48): error CS7036: There is no argument given that corresponds to the required formal parameter 'assemblyLoadContext' of 'RuntimeAssembly.InternalLoadAssemblyName(AssemblyName, ref StackCrawlMark, AssemblyLoadContext)' [/home/vsts/work/1/s/mcs/class/System.Private.CoreLib/System.Private.CoreLib.csproj]
/home/vsts/work/1/s/netcore/System.Private.CoreLib/shared/System/Text/ASCIIUtility.cs(1350,30): error CS1503: Argument 1: cannot convert from 'ulong*' to 'double*' [/home/vsts/work/1/s/mcs/class/System.Private.CoreLib/System.Private.CoreLib.csproj]
/home/vsts/work/1/s/netcore/System.Private.CoreLib/shared/System/Text/ASCIIUtility.cs(1350,52): error CS1503: Argument 2: cannot convert from 'System.Runtime.Intrinsics.Vector128<ulong>' to 'System.Runtime.Intrinsics.Vector128<double>' [/home/vsts/work/1/s/mcs/class/System.Private.CoreLib/System.Private.CoreLib.csproj]
/home/vsts/work/1/s/netcore/System.Private.CoreLib/shared/System/Text/ASCIIUtility.cs(1389,34): error CS1503: Argument 1: cannot convert from 'ulong*' to 'double*' [/home/vsts/work/1/s/mcs/class/System.Private.CoreLib/System.Private.CoreLib.csproj]
/home/vsts/work/1/s/netcore/System.Private.CoreLib/shared/System/Text/ASCIIUtility.cs(1389,84): error CS1503: Argument 2: cannot convert from 'System.Runtime.Intrinsics.Vector128<ulong>' to 'System.Runtime.Intrinsics.Vector128<double>' [/home/vsts/work/1/s/mcs/class/System.Private.CoreLib/System.Private.CoreLib.csproj]
/home/vsts/work/1/s/netcore/System.Private.CoreLib/shared/System/Text/ASCIIUtility.cs(1465,30): error CS1503: Argument 1: cannot convert from 'ulong*' to 'double*' [/home/vsts/work/1/s/mcs/class/System.Private.CoreLib/System.Private.CoreLib.csproj]
/home/vsts/work/1/s/netcore/System.Private.CoreLib/shared/System/Text/ASCIIUtility.cs(1465,80): error CS1503: Argument 2: cannot convert from 'System.Runtime.Intrinsics.Vector128<ulong>' to 'System.Runtime.Intrinsics.Vector128<double>' [/home/vsts/work/1/s/mcs/class/System.Private.CoreLib/System.Private.CoreLib.csproj]
/home/vsts/work/1/s/netcore/System.Private.CoreLib/shared/System/Marvin.OrdinalIgnoreCase.cs(37,22): error CS0103: The name 'Utf16Utility' does not exist in the current context [/home/vsts/work/1/s/mcs/class/System.Private.CoreLib/System.Private.CoreLib.csproj]
/home/vsts/work/1/s/netcore/System.Private.CoreLib/shared/System/Marvin.OrdinalIgnoreCase.cs(41,23): error CS0103: The name 'Utf16Utility' does not exist in the current context [/home/vsts/work/1/s/mcs/class/System.Private.CoreLib/System.Private.CoreLib.csproj]
/home/vsts/work/1/s/netcore/System.Private.CoreLib/shared/System/Marvin.OrdinalIgnoreCase.cs(60,23): error CS0103: The name 'Utf16Utility' does not exist in the current context [/home/vsts/work/1/s/mcs/class/System.Private.CoreLib/System.Private.CoreLib.csproj]
```

Looks like fallout from https://github.com/mono/mono/pull/14163

I'll take a look - filing an issue so there's a record.

**Comment by directhex** [comment]
PendingUnmanagedWorkItemCount is implemented as an internal in CoreCLR, in https://github.com/dotnet/coreclr/pull/24113/files#diff-b9c0d933a963667fa9aecdd26c410c84 - we don't have an equivalent. Hence the breakage there.

**Comment by directhex** [comment]
AsciiUtility failures came in with 2119795cae24, which changed:

```
-            Sse2.StoreLow((ulong*)pAsciiBuffer, asciiVector.AsUInt64()); // ulong* calculated here is UNALIGNED
+            Sse2.StoreScalar((ulong*)pAsciiBuffer, asciiVector.AsUInt64()); // ulong* calculated here is UNALIGNED
```
StoreLow used to take `ulong* address, Vector128<ulong> source` but 
StoreScalar takes `double* address, Vector128<double> source` - we lack implicit casts here

**Comment by vargaz** [comment]
Isn't there a netcore CI lane ?

**Comment by directhex** [comment]
Marvin.OrdinalIgnoreCase errors are due to a missing change in this sync - we lack https://github.com/dotnet/coreclr/commit/effeb6ee79ca64376775a81ef1b2d9b507a30163 which changed `using System.Text;` to `using System.Text.Unicode;`

**Comment by directhex** [comment]
@vargaz yes but it seems to have stopped running? Let me check why.

**Comment by directhex** [comment]
No, it did run as expected, and failed on the PR in question https://dev.azure.com/dnceng/public/_build/results?buildId=172632

**Comment by vargaz** [comment]
The PR doesn't show that lane:
https://github.com/mono/mono/pull/14163

**Comment by directhex** [comment]
Yeah, so I see. I'm trying to figure out what's going on with the job. It's definitely _running_

**Comment by directhex** [comment]
Seems it is? https://github.com/mono/mono/pull/14163/checks

But it's not in the list of "38 checks"

38 is actually low for us so might have glitched in other ways

:man_shrugging:

**Comment by directhex** [comment]
Looks like a bug on GitHub's end - the lane failed on the last commit in the PR, but not in the "35 of 38 checks succeeded" window - but the way you set status in the GitHub API is by setting status on the commit. If you click the red X next to f318317 you can clearly see the failed lane.

**Comment by marek-safar** [comment]
It should work, there was sync issue again after the large nullable change landed
