### ISSUE TITLE
Local functions not supported in Debian Mono Package

### ISSUE THREAD

**Issue by mateusz-holenko** [mono/mono#19984]
Mono from the official Debian package fails to compile C# code using local functions. 

Note: The example attached below compiles fine on a Mono package from Xamarin channel  (http://download.mono-project.com/repo/debian).

## Steps to Reproduce

1. Save the code below to the test.cs file
2. Execute `xbuild`

```
using System;

public static class MainClass
{
    public static void Main(string[] args)
    {
        System.Console.Write("Hello ");
        InnerF();

        void InnerF()
        {
            System.Console.WriteLine("world!");
        }
    }
}
```

### Current Behavior

The compilation fails with:

```
/root/test_csharp/test.csproj (default targets) ->
/usr/lib/mono/xbuild/14.0/bin/Microsoft.CSharp.targets (CoreCompile target) ->

        test.cs(10,3): error CS1547: Keyword `void' cannot be used in this context
        test.cs(10,13): error CS1525: Unexpected symbol `(', expecting `,', `;', or `='
        test.cs(15): error CS1525: Unexpected symbol `}'

         0 Warning(s)
         3 Error(s)
```

### Expected Behavior

The compilation should succeed an the code should print "Hello world!".

## On which platforms did you notice this

[ ] macOS
[x] Linux
[ ] Windows

**Version Used**:

Both sources (Xamarin and Debian) provide the same version of mono: 6.8.0.105

**Comment by akoeplinger** [comment]
This is most likely because the Debian sources use the old `mcs` compiler rather than the new `csc` (Roslyn) that supports local functions.

@directhex is that correct?

**Comment by mateusz-holenko** [comment]
@akoeplinger This might be the reason - I noticed that Xamarin's package compiles using `/usr/lib/mono/4.5/csc.exe`, whereas the default Debian one uses `/usr/lib/mono/4.5/mcs.exe`.

For testing purposes, I installed additionally `mono-mcs` package and tried the `mono-csc` compiler manually, but it didn't help either (the result was the same - it failed to compile the attached sample).

**Comment by PiotrZierhoffer** [comment]
@akoeplinger do you know if there is anyone who could give us some info if there is any plan to change the current situation?

**Comment by akoeplinger** [comment]
@PiotrZierhoffer the `mono-mcs` package still installs the `mcs` compiler.

Only the Roslyn `csc` supports these new features and right now Debian doesn't allow shipping it since we can't easily build it from source (in the Xamarin packages we ship the binary .exe).

**Comment by PiotrZierhoffer** [comment]
@akoeplinger Thanks. Can we safely assume that this is not something that will change in the foreseeable future?

I don't believe Debian rules will change, but maybe you are aware of any work on the csc build process?

**Comment by akoeplinger** [comment]
Yeah this won't change for the version of mono that is in Debian's official repositories.

There is work as part of the larger .NET unification efforts that will produce from-source builds of the whole .NET SDK (https://github.com/dotnet/source-build), which should allow inclusion into Debian.
