### ISSUE TITLE
MSBuildSDKsPath error in XI with latest 2019-02 Mono/msbuild package

### ISSUE THREAD

**Issue by akoeplinger** [mono/mono#14765]
## Steps to Reproduce

1. Install recent 2019-02 Mono .pkg
2. Clone https://github.com/xamarin/xamarin-macios
3. Checkout master branch at 17d73975c8aea925ba83b20f401e743330928c35
4. Run `./configure --enable-xamarin` and `make world`
5. It fails with an msbuild error while compiling mlaunch.app

### Current Behavior

```
GEN      mlaunch.app
MSBUILD: error MSB4136: Error reading the configuration information from "System.Configuration". Error deserializing configuration section msbuildToolsets: Multiple definitions for the MSBuildSDKsPath property.
```

Note: error message was translated from German so may not match 100%.

A workaround is to comment out the MSBuildSDKsPath property in `/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/msbuild/15.0/bin/MSBuild.dll.config`

This started happening with a recent 2019-02 build, it works fine with 6.0.0.176. I guess it's related to the msbuild environment variables that the xibuild tool sets.

### Expected Behavior

No error.

## On which platforms did you notice this

[ x ] macOS
[ ] Linux
[ ] Windows

**Version Used**: 6.0.0.275 (2019-02/8ff6a12f510)

**Comment by lewing** [comment]
Android handles this slightly differently https://github.com/xamarin/xamarin-android/blob/cfe1f9ad27dd3c6044041ab75e948f6a5350fb0b/tools/xabuild/XABuild.cs#L125 is it also having problems?

**Comment by lewing** [comment]
#13537 is also sdk project related
