### ISSUE TITLE
Transform.c:2856, condition `<disabled>' not met

### ISSUE THREAD

**Issue by jeromelaban** [mono/mono#12981]
When running a wasm binary under the interpreter with debugging enabled, the following error can occur:
```
* Assertion at /mnt/jenkins/workspace/test-mono-mainline-wasm/label/ubuntu-1804-amd64/mono/mini/interp/transform.c:2856, condition `<disabled>' not met
```

## Steps to Reproduce

1. In Visual Studio 2017/2019, open [this solution](https://github.com/nventive/Uno.Xaml-Controls-Gallery/blob/uno/XamlControlsGallery.Windows/XamlControlsGallery.sln) at commit https://github.com/nventive/Uno.Xaml-Controls-Gallery/commit/f1be090d0183f49c9ad697b90215e69324f99285.
2. Select the XamlControlsGallery.Wasm project
3. Ensure that the active configuration is `Debug`
4. Run the project with `Ctrl+F5`
5. Once the app has started click on any item in the left list

### Current Behavior
There's an assertion in the runtime's interpreter.

### Expected Behavior
A managed exception is raised. There's really an issue in this commit of the repo, where an NRE is raised.

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[ ] Windows
[X] WebAssembly

**Version Used**: 5f65ce9f7dfa6404219c90b6b82ba586fabb2e1c

## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by jeromelaban** [comment]
Here's a repro:
```
static void Main(string[] args) => MethodA(null);

internal static bool MethodA(object sender)
{
    if (sender == null) { return true; }
    return MethodA(sender);
}
```
the issue happens only in release configutation.

See here for the full repro: https://github.com/jeromelaban/Wasm.Samples/tree/master/Bug12981-InterpRecursion/BugInterpRecursion

**Comment by kjpou1** [comment]
@jeromelaban Is this still an issue?

I have taken your sample above and created both a Debug version and a Release version here using full linkage and can not reproduce this.

Sample code from: https://github.com/jeromelaban/Wasm.Samples/tree/master/Bug12981-InterpRecursion/BugInterpRecursion

Release mode:

```
Loaded: System.Drawing.Common.dll
Loaded: WebAssembly.Net.WebSockets.dll
Loaded: System.Web.Services.dll
Loaded: WasmCoreObjects.dll
Loaded: WebAssembly.Bindings.dll
Loaded: WebAssembly.Net.Http.dll
Loaded: System.dll
Loaded: System.Net.Http.dll
Loaded: mscorlib.dll
initializing mono runtime
>>mono_wasm_runtime_ready
Called internal static bool MethodA(object sender) from static void MainA(string[] args) => MethodA(null);
Total Memory Exit WASM: 33554432
```

```

Loaded: System.Drawing.Common.dll
Loaded: System.Web.Services.dll
Loaded: WasmCoreObjects.dll
Loaded: WebAssembly.Bindings.dll
Loaded: WebAssembly.Net.Http.dll
Loaded: WebAssembly.Net.WebSockets.dll
Loaded: System.Drawing.Common.pdb
Loaded: System.Net.Http.pdb
Loaded: System.Web.Services.pdb
Loaded: System.pdb
Loaded: System.dll
Loaded: WasmCoreObjects.pdb
Loaded: WebAssembly.Bindings.pdb
Loaded: WebAssembly.Net.Http.pdb
Loaded: WebAssembly.Net.WebSockets.pdb
Loaded: System.Net.Http.dll
Loaded: mscorlib.pdb
Loaded: mscorlib.dll
initializing mono runtime
DEBUGGING ENABLED
>>mono_wasm_runtime_ready
﻿Called internal static bool MethodA(object sender) from static void MainA(string[] args) => MethodA(null);
Total Memory Exit WASM: 33554432

```

**Comment by kjpou1** [comment]
@lewing ^

**Comment by kjpou1** [comment]
@lewurm do you think we can close this?  Have run the tests above as well as included it in the wasm tests.  Maybe I am missing something with the repro of the issue.

**Comment by jeromelaban** [comment]
I will check this again today and will let you know, thanks!

**Comment by jeromelaban** [comment]
@kjpou1 it still fails with 22bbf4416a6, with this repro: https://github.com/jeromelaban/Wasm.Samples/tree/master/Bug12981-InterpRecursion/BugInterpRecursion.

Note that the build has to be made in release configuration (most probably if the `/optimize` switch is added to csc).

```
Stacktrace: 

mono.js:1 Error
    at Array.ASM_CONSTS (mono.js:1)
    at _emscripten_asm_const_i (mono.js:1)
    at :64317/wasm-function[6072]:18
    at :64317/wasm-function[3863]:38
    at :64317/wasm-function[3730]:41
    at :64317/wasm-function[2135]:44
    at :64317/wasm-function[143]:33
    at :64317/wasm-function[5649]:175
    at :64317/wasm-function[5733]:93
    at :64317/wasm-function[5750]:441
mono.js:1 * Assertion at /mnt/jenkins/workspace/test-mono-mainline-wasm/label/ubuntu-1804-amd64/mono/mini/interp/transform.c:5440, condition `<disabled>' not met
put_char @ mono.js:1
uno-bootstrap.js:147 abort(). Build with -s ASSERTIONS=1 for more info.
```

**Comment by vargaz** [comment]
I can't reproduce it either. Could you attach the .exe file ?

**Comment by jeromelaban** [comment]
Sure: [dist.zip](https://github.com/mono/mono/files/3073326/dist.zip)

**Comment by vargaz** [comment]
I can reproduce with the assemblies from that zip file.

**Comment by vargaz** [comment]
There seems to be a problem with the BugInterpRecursion.clr file. If I run ildasm+ilasm on it, the problem goes away.

**Comment by jeromelaban** [comment]
Could it be related to the linker, or a combination of CSC + ILinker ? I'm building using VS2019 16.0.

**Comment by vargaz** [comment]
Seems to be because ins->il_offset == td->header->code_size at transform.c, because of the tailcall opt in transform_call () does this:
				++td->ip; /* gobble the CEE_RET if it isn't branched to */				
and after that, it does:

				last_seq_point = interp_add_ins (td, MINT_SDB_SEQ_POINT);
				// This seq point is actually associated with the instruction following the call
				last_seq_point->il_offset = td->ip - header->code;
				last_seq_point->flags = INTERP_INST_FLAG_SEQ_POINT_NONEMPTY_STACK;

**Comment by joer33304** [comment]
This issue still appears for me using latest production 5.0 version.

**Comment by akoeplinger** [comment]
@joer33304 please open a new issue on https://github.com/dotnet/runtime/issues with a sample project that reproduces the issue.
