### ISSUE TITLE
(regression) SIGSEGV in RuntimeMethodInfo:InternalInvoke with xunit

### ISSUE THREAD

**Issue by kekekeks** [mono/mono#13969]
Environment: 
Ubuntu 16.04 Azure Pipelines image with
`Mono JIT compiler version 5.18.0.268 (tarball Thu Feb 28 15:29:06 UTC 2019)`

was working completely fine with 
`Mono JIT compiler version 5.18.0.240 (tarball Wed Jan 16 09:13:03 UTC 2019)`

Repro:
```
git clone --recursive git@github.com:AvaloniaUI/Avalonia.git
cd Avalonia
sudo apt-get update && sudo apt-get install castxml
dotnet tool install --global Nuke.GlobalTool --version 0.12.3
nuke --target CiAzureLinux --configuration=Release
```

One of xunit test assemblies segfaults like this https://dev.azure.com/AvaloniaUI/AvaloniaUI/_build/results?buildId=1851&view=logs&jobId=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&taskId=d9b15392-e4ce-5e4c-0c8c-b69645229181&lineStart=1132&lineEnd=1133&colStart=1&colEnd=1

I've also checked with mono built from master, still segfaults, but I'm also seeing messages like these:
```
ves_icall_TypeBuilder_create_runtime_class_raw USED 151 handles
ves_icall_TypeBuilder_create_runtime_class_raw USED 156 handles
ves_icall_TypeBuilder_create_runtime_class_raw USED 104 handles
ves_icall_TypeBuilder_create_runtime_class_raw USED 108 handles
ves_icall_TypeBuilder_create_runtime_class_raw USED 158 handles
```

Not sure if that's relevant.

Also reproduced on OSX with `MonoFramework-MDK-5.18.0.268.macos10.xamarin.universal.pkg`, works fine with 5.18.0.225.

**Comment by jaykrell** [comment]
Must be handle creation in a loop.

I tried building Avalonia.
I could not get `nuke` to run and `build.sh` failed.

```
jay@jaykrell-tp2:/mnt/c/s/Avalonia$ sh -c ./build.sh
GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu)
Microsoft (R) .NET Core SDK version 2.2.203
Shims.cs(8,7): error CS0246: The type or namespace name 'Numerge' could not be found (are you missing a using directive or an assembly reference?) [/mnt/c/s/Avalonia/nukebuild/_build.csproj]
Shims.cs(81,31): error CS0246: The type or namespace name 'INumergeLogger' could not be found (are you missing a using directive or an assembly reference?) [/mnt/c/s/Avalonia/nukebuild/_build.csproj]
Shims.cs(83,25): error CS0246: The type or namespace name 'NumergeLogLevel' could not be found (are you missing a using directive or an assembly reference?) [/mnt/c/s/Avalonia/nukebuild/_build.csproj]

The build failed. Please fix the build errors and run again.
jay@jaykrell-tp2:/mnt/c/s/Avalonia$  nuke
nuke: command not found
jay@jaykrell-tp2:/mnt/c/s/Avalonia$ dotnet nuke
No executable found matching command "dotnet-nuke"
jay@jaykrell-tp2:/mnt/c/s/Avalonia$
```

**Comment by kekekeks** [comment]
That's what we are using on CI:

> dotnet tool install --global Nuke.GlobalTool --version 0.12.3
> nuke --target CiAzureLinux --configuration=Release

That should work. You also need `castxml` installed.

**Comment by jaykrell** [comment]
It doesn't work for me. I'm using WSL instead of "real" Linux.
I can try a VM "later".

This part is promising:
```
jay@jaykrell-tp2:/mnt/c/s/Avalonia/samples/ControlCatalog.NetCore$ dotnet run

Unhandled Exception: System.Exception: XOpenDisplay failed
   at Avalonia.X11.AvaloniaX11Platform.Initialize(X11PlatformOptions options) in /mnt/c/s/Avalonia/src/Avalonia.X11/X11Platform.cs:line 36
   at Avalonia.AvaloniaX11PlatformExtensions.<>c__0`1.<UseX11>b__0_0() in /mnt/c/s/Avalonia/src/Avalonia.X11/X11Platform.cs:line 105
  ```

**Comment by jaykrell** [comment]
Maybe I was missing the git submodule. or WSL had to restart. It is build now.

**Comment by jaykrell** [comment]
`build.sh` got all the way to running tests. Using dot net, not mono.
`nuke` wouldn't work at all.

**Comment by jaykrell** [comment]
To fix `nuke`: ` export PATH=$HOME/.dotnet/tools:$PATH`

**Comment by kekekeks** [comment]
Reproduced with MonoFramework-MDK-5.18.0.268.macos10.xamarin.universal.pkg on OSX
https://dev.azure.com/AvaloniaUI/AvaloniaUI/_build/results?buildId=1871&view=logs&jobId=a5e52b91-c83f-5429-4a68-c246fc63a4f7&taskId=bde16fc7-7659-5b1c-12aa-0110866d993c&lineStart=1044&lineEnd=1045&colStart=1&colEnd=1

**Comment by lewurm** [comment]
relevant crashing info:
```
       frame #0: 0x00007fff6690522a libsystem_kernel.dylib`__wait4 + 10
       frame #1: 0x000000010b96edc0 mono`mono_dump_native_crash_info at mini-posix.c:1112 [opt]
       frame #2: 0x000000010b96eb04 mono`mono_dump_native_crash_info(signal=<unavailable>, ctx=<unavailable>, info=<unavailable>) at mini-posix.c:1149 [opt]
       frame #3: 0x000000010b912345 mono`mono_handle_native_crash(signal="SIGSEGV", ctx=0x0000000000000000, info=0x0000000000000000) at mini-exceptions.c:3290 [opt]
       frame #4: 0x000000010b968eb6 mono`altstack_handle_and_restore(ctx=0x000070000792f6d0, obj=0x0000000000000000, stack_ovf=0) at exceptions-amd64.c:858 [opt]
       frame #5: 0x000000010bb58ca0 mono`mono_gc_memmove_aligned(dest=<unavailable>, src=<unavailable>, size=<unavailable>) at memfuncs.c:193 [opt]
       frame #6: 0x000000010baf105f mono`mono_gc_wbarrier_value_copy(dest=0x000000010c30b8a8, src=0x0000000000000000, count=1, klass=0x00007ff600001ec8) at sgen-mono.c:112 [opt]
       frame #7: 0x000000010ba6dede mono`mono_value_box_checked(domain=<unavailable>, klass=0x00007ff600001ec8, value=0x0000000000000000, error=0x000070000792fa60) at object.c:6866 [opt]
       frame #8: 0x000000010ba6d706 mono`mono_runtime_try_invoke_array(method=<unavailable>, obj=<unavailable>, params=0x000000010c30b670, exc=0x0000000000000000, error=0x000070000792fa60) at object.c:5383 [opt]
       frame #9: 0x000000010ba19fe9 mono`ves_icall_InternalInvoke(method=<unavailable>, this_arg=<unavailable>, params=0x000000010c30b670, exc=0x000070000792fbe0) at icall.c:3465 [opt]
       frame #10: 0x000000010e51d8d1
       frame #11: 0x000000010db98a1b mscorlib.dll.dylib`System_Reflection_MethodBase_Invoke_object_object__ + 43
       frame #12: 0x000000011077001b
```
@kekekeks is it possible for you to try a newer version? latest is `5.18.1.14`. `5.18.1.7` shipped a fix in the AMD64 codegen;  to be honest, it doesn't look like it from the stack trace, but it's worth a try.

**Comment by kekekeks** [comment]
@lewing MonoFramework-MDK-5.20.1.19.macos10.xamarin.universal.pkg still segfaults

**Comment by lambdageek** [comment]
Hmm `mono_value_box_checked(domain=<unavailable>, klass=0x00007ff600001ec8, value=0x0000000000000000, error=0x000070000792fa60) at object.c:6866 ` we're trying to box a null value.  suspicious...

**Comment by kekekeks** [comment]
We've disabled Mono tests on Linux for now. To repro the issue with the latest Avalonia, use `FORCE_LINUX_TESTS=1` environment variable.
