### ISSUE TITLE
Runtime Exception (Garbage collector could not allocate 16384 bytes) in Blazor client-side since 3.2

### ISSUE THREAD

**Issue by mkArtakMSFT** [mono/mono#18617]
_From @GillCleeren on Wednesday, January 29, 2020 4:58:35 PM_

### Describe the bug
Exception is thrown when registering types with AutoMapper at runtime. 

### To Reproduce

In Program.cs:

`var builder = WebAssemblyHostBuilder.CreateDefault(args);

            var automapperConfig = new MapperConfiguration(configuration =>
            {
                configuration.AddProfile(new CustomMappings());
            });

            var autoMapper = automapperConfig.CreateMapper();

            builder.Services.AddSingleton(autoMapper);`

CustomMapping.cs contains (quite a few) mappings:
`public class CustomMappings : MapperConfigurationExpression
    {
        public CustomMappings()
        {
            CreateMap<WitnessDto, WitnessGeneralInfoViewModel>();
            CreateMap<WitnessGeneralInfoViewModel, WitnessDto >();`

The error is only happening when I create a large(r) number of mappings with their reverse (more than 15). Same happens with using ReverseMap.

The memory use of Chrome running this goes up over 2.1GB whereas the 3.1 version is around 150MB.

When running this code in 3.2 (update of Jan 28), I get the error below. The exact same code works in 3.1.

Here's the browser console output.
blazor.webassembly.js:1 WASM: Error: Garbage collector could not allocate 16384 bytes of memory for major heap section.
l.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM: [object Object]
l.printErr @ blazor.webassembly.js:1
dotnet.js:1 Stacktrace: 

dotnet.js:1 Error
    at 650764 (dotnet.js:1)
    at _emscripten_asm_const_iii (dotnet.js:1)
    at :5001/wasm-function[3493]:0xab8a1
    at :5001/wasm-function[3796]:0xb9f77
    at :5001/wasm-function[3661]:0xb4e6d
    at :5001/wasm-function[2136]:0x65002
    at :5001/wasm-function[150]:0x3a1c
    at :5001/wasm-function[3892]:0xbe69e
    at :5001/wasm-function[3894]:0xbe87f
    at :5001/wasm-function[1243]:0x38052
blazor.webassembly.js:1 WASM: * Assertion at /mnt/jenkins/workspace/test-mono-mainline-wasm/label/ubuntu-1804-amd64/mono/utils/lock-free-alloc.c:145, condition `sb_header' not met, function:alloc_sb, Failed to allocate memory for the lock free allocator
l.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM: undefined
blazor.webassembly.js:1 WASM: undefined
l.printErr @ blazor.webassembly.js:1
dotnet.js:1 Uncaught RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info.
    at abort (https://localhost:5001/_framework/wasm/dotnet.js:1:16107)
    at _abort (https://localhost:5001/_framework/wasm/dotnet.js:1:117299)
    at wasm-function[3493]:0xab8ae
    at wasm-function[3796]:0xb9f77
    at wasm-function[3661]:0xb4e6d
    at wasm-function[2136]:0x65002
    at wasm-function[150]:0x3a1c
    at wasm-function[3892]:0xbe69e
    at wasm-function[3894]:0xbe87f
    at wasm-function[1243]:0x38052
### Further technical details
- Blazor 3.2 Preview 1

_Copied from original issue: dotnet/aspnetcore#18659_

**Comment by alexprogrammr** [comment]
Hi!

Are there any updates on this issue?
I'm having the same problem running client-side Blazor 5.0.

**Comment by 1618employment** [comment]
Hi!

Same!

- dotnet version 5.0.406
- blazor WASM standalone
- seems to occur most often after an async/await network request, but request doesn't return much data (kb not mb)
- I'm not running telerik, but looks like similar issue [here](https://docs.telerik.com/blazor-ui/knowledge-base/dpl-allocate-memory-error)
- old stackoverflow.com regarding mono and xamarin suggests messing with GC (scary) [here](https://stackoverflow.com/questions/27685375/garbage-collector-could-not-allocate-16384-bytes-of-memory-for-major-heap-sectio) 

Is this a configuration issue with mono or poor coding on my part (memory leak)? How would I isolate?

Thank You!

Error: Garbage collector could not allocate 16384u bytes of memory for major heap section.
Error: Garbage collector could not allocate 16384u bytes of memory for major heap section.
Error: Garbage collector could not allocate 16384u bytes of memory for major heap section.
Error: Garbage collector could not allocate 16384u bytes of memory for major heap section.
Error: Garbage collector could not allocate 16384u bytes of memory for major heap section.
Error: Garbage collector could not allocate 16384u bytes of memory for major heap section.
Error: Garbage collector could not allocate 16384u bytes of memory for major heap section.
Error: Garbage collector could not allocate 16384u bytes of memory for major heap section.
Error: Garbage collector could not allocate 16384u bytes of memory for major heap section.
Error: Garbage collector could not allocate 16384u bytes of memory for major heap section.
Error: Garbage collector could not allocate 16384u bytes of memory for major heap section.
Error: Garbage collector could not allocate 16384u bytes of memory for major heap section.
Error: Garbage collector could not allocate 16384u bytes of memory for major heap section.
Error: Garbage collector could not allocate 16384u bytes of memory for major heap section.
Error: Garbage collector could not allocate 16384u bytes of memory for major heap section.
Uncaught ExitStatusError: Garbage collector could not allocate 16384u bytes of memory for major heap section.
Uncaught ExitStatusError: Garbage collector could not allocate 16384u bytes of memory for major heap section.
Uncaught ExitStatusUncaught ExitStatusUncaught ExitStatusUncaught ExitStatusUncaught ExitStatusUncaught ExitStatusUncaught ExitStatusUncaught ExitStatusUncaught ExitStatusUncaught ExitStatusUncaught ExitStatusUncaught ExitStatusUncaught ExitStatusUncaught ExitStatusUncaught ExitStatus: * Assertion at /__w/1/s/src/mono/mono/utils/lock-free-alloc.c:145, condition `sb_header' not met, function:alloc_sb, Failed to allocate memory for the lock free allocator

: * Assertion at /__w/1/s/src/mono/mono/utils/lock-free-alloc.c:145, condition `sb_header' not met, function:alloc_sb, Failed to allocate memory for the lock free allocator

Uncaught ExitStatus

**Comment by didyk** [comment]
Same problem for me. Blazor 5.0.

**Comment by kmkrish001** [comment]
Thwesame issue occurs for me with Blazor 6.0.

![image](https://user-images.githubusercontent.com/92425146/167825183-c0d9b255-1a19-48e2-9b89-94260b15feb5.png)

**Comment by mortech69** [comment]
Issue in Blazor WebAssembly 7.0.10
![Capture](https://github.com/mono/mono/assets/96631947/c2017f92-e375-4724-b782-1c89ff6178ed)

**Comment by AlexanderMagdysyuk** [comment]
Reproduced with .NET 8.0.12 too.

**Comment by akoeplinger** [comment]
This is the legacy mono/mono repository, modern Blazor uses the mono runtime from https://github.com/dotnet/runtime.
Please file an issue about the GC issue there, preferably with a sample project that reproduces the problem.
