### PR TITLE
[MonoContext] Migrate remaining architectures + [sgen] Kill USE_MONO_CTX and ARCH_NUM_REGS

### PR DESCRIPTION
**Pull request by ludovic-henry**

### CODE REVIEW

**Comment by ludovic-henry** [comment]
@vargaz @kumpera could you please review? Thank you :)

**Comment by vargaz** [comment]
Looks ok.

**Comment by lewurm** [comment]
this breaks the monodroid build:
```
[10:28:06] Processing triple: armv5-none-linux-androideabi
[10:28:07] Parsed '/Users/builder/data/lanes/1845/3265991e/source/mono/mono/metadata/metadata-cross-helpers.c'
[10:28:07] Parsed '/Users/builder/data/lanes/1845/3265991e/source/mono/mono/mini/mini-cross-helpers.c'
[10:28:07] Generated offsets file: /Users/builder/data/lanes/1845/3265991e/source/monodroid/builds/cross/armv6/armv5-none-linux-androideabi.h
[10:28:07] /Applications/Xcode62.app/Contents/Developer/usr/bin/make -s -C /Users/builder/data/lanes/1845/3265991e/source/monodroid/builds/cross/armv6/mono/arch/arm arm_dpimacros.h
[10:28:07] /Applications/Xcode62.app/Contents/Developer/usr/bin/make -s -C /Users/builder/data/lanes/1845/3265991e/source/monodroid/builds/cross/armv6/mono/arch/arm arm_vfpmacros.h
[10:28:07] /Applications/Xcode62.app/Contents/Developer/usr/bin/make -s -C /Users/builder/data/lanes/1845/3265991e/source/monodroid/builds/cross/armv6
[10:28:07] Making all in po
[10:28:07] Making all in mcs
[10:28:07] Making all in eglib
[10:28:07] Making all in m4
[10:28:07] Making all in src
[10:28:07]   CC       libeglib_la-gbytearray.lo
[10:28:07]   CC       libeglib_la-gerror.lo
[10:28:07]   CC       libeglib_la-garray.lo
[...]
[10:28:40]   CC       libmini_la-mini-codegen.lo
[10:28:40]   CC       libmini_la-mini-exceptions.lo
[10:28:40]   CC       libmini_la-mini-exceptions-native-unwinder.lo
[10:28:41] /Users/builder/data/lanes/1845/3265991e/source/mono/mono/mini/mini-exceptions.c:1511:19: error: no member named 'regs' in 'MonoContext'
[10:28:41]       do { (ctx)->regs [0] = (gsize)ex_obj; } while (0);
[10:28:41]            ~~~~~  ^
[10:28:41] /Users/builder/data/lanes/1845/3265991e/source/mono/mono/mini/mini-exceptions.c:1825:18: error: no member named 'regs' in 'MonoContext'
[10:28:41]      do { (ctx)->regs [0] = (gsize)ex_obj; } while (0);
[10:28:41]           ~~~~~  ^
[10:28:41] 2 errors generated.
[10:28:41] make[7]: *** [libmini_la-mini-exceptions.lo] Error 1
[10:28:41] make[7]: *** Waiting for unfinished jobs....```

**Comment by lewurm** [comment]
I guess that's the fix? ad78b9f5acb6c6462f300c13a923ebe427551808 @vargaz ?

**Comment by vargaz** [comment]
Hopefully.

**Comment by akoeplinger** [comment]
The monodroid build is still broken even after ad78b9f:
```
[5:01:27]   CC       libmini_la-mini-arm-gsharedvt.lo
[5:01:27] /Users/builder/data/lanes/1845/65ab352d/source/mono/mono/mini/mini-arm.c:7277:14: error: no member named 'regs' in 'MonoContext'
[5:01:27]  return ctx->regs [reg];
[5:01:27]         ~~~  ^
[5:01:27] /Users/builder/data/lanes/1845/65ab352d/source/mono/mono/mini/mini-arm.c:7283:7: error: no member named 'regs' in 'MonoContext'
[5:01:27]  ctx->regs [reg] = val;
[5:01:27]  ~~~  ^
[5:01:27] /Users/builder/data/lanes/1845/65ab352d/source/mono/mono/mini/mini-arm.c:7513:1: warning: no previous prototype for function 'mono_arch_get_seq_point_info' [-Wmissing-prototypes]
[5:01:27] mono_arch_get_seq_point_info (MonoDomain *domain, guint8 *code)
[5:01:27] ^
[5:01:27] /Users/builder/data/lanes/1845/65ab352d/source/mono/mono/mini/mini-arm.c:7544:1: warning: no previous prototype for function 'mono_arch_init_lmf_ext' [-Wmissing-prototypes]
[5:01:27] mono_arch_init_lmf_ext (MonoLMFExt *ext, gpointer prev_lmf)
[5:01:27] ^
[5:01:27] 2 warnings and 2 errors generated.
[5:01:27] make[7]: *** [libmini_la-mini-arm.lo] Error 1
```
