### ISSUE TITLE
FreeBSD building broken by #19438

### ISSUE THREAD

**Issue by rootwyrm** [mono/mono#19733]
All building is broken by #19438 with a compiler error. Caused by commit https://github.com/mono/mono/commit/429d269d0f83e6b382b8d36930a5fdb2b066b618

```
mini-posix.c:694:19: error: incompatible pointer types passing 'clockid_t *' (aka 'int *') to parameter of type 'mono_clock_id_t *' (aka 'void **') [-Werror,-Wincompatible-pointer-types]
```

**Comment by akoeplinger** [comment]
@fanyang-mono

**Comment by rootwyrm** [comment]
Entirely my bad not noticing the CI breakage when this went in. Had to do some homework here to try figure out what's going on. Turns out this would also be broken on older OSX since it's the same code (later versions added a shim.) I'm also half-wondering if some of this shouldn't ifdef to a FreeBSD-specific clock (`CLOCK_MONOTONIC_PRECISE` or `CLOCK_MONOTONIC_FAST`) to see if that resolves some pains but I really don't grok this code well enough to say for sure.

But what's really got me scratching my head though, is that this was working previously and there doesn't appear to be any particular reason it should have _stopped_ working.

**Comment by fanyang-mono** [comment]
I will have to look into it as well. What I did was basically a refactor work. Not sure how it would change the behavior for building on FreeBSD.

**Comment by rootwyrm** [comment]
Yeah.. my initial thought was that perhaps there was a double definition somewhere, but no such luck. Did some additional digging and found something in base I could use as a reference, and it pretty clearly shows that everything here _should_ be correct.

**Comment by rootwyrm** [comment]
@fanyang-mono bad news... 6.8.0.123 definitely exposed something in here. Permanent hang in thread states during compile. Attached a ktrace, and it's definitely clock-induced thread problems.

```
  8900 mono-sgen CALL  _umtx_op(0x803da4064,UMTX_OP_CV_WAIT,0x6<CVWAIT_ABSTIME|CVWAIT_CLOCKID>,0x800c8e280,0x7fffd97c8dc0)
  8900 mono-sgen RET   _umtx_op -1 errno 60 Operation timed out
  8900 mono-sgen CALL  clock_gettime(0x4,0x7fffd97c8dc8)
  8900 mono-sgen RET   clock_gettime 0
  8900 mono-sgen CALL  clock_gettime(0x4,0x7fffd97c8e58)
  8900 mono-sgen RET   clock_gettime 0
  8900 mono-sgen CALL  clock_gettime(0x4,0x7fffd97c8e58)
  8900 mono-sgen RET   clock_gettime 0
  8900 mono-sgen CALL  clock_gettime(0x4,0x7fffd97c8dc8)
  8900 mono-sgen RET   clock_gettime 0
  8900 mono-sgen CALL  clock_gettime(0x4,0x7fffd97c8dc8)
  8900 mono-sgen RET   clock_gettime 0
  8900 mono-sgen CALL  clock_gettime(0x4,0x7fffd97c8dc0)
  8900 mono-sgen RET   clock_gettime 0
  8900 mono-sgen CALL  _umtx_op(0x803da4064,UMTX_OP_CV_WAIT,0x6<CVWAIT_ABSTIME|CVWAIT_CLOCKID>,0x800c8e280,0x7fffd97c8dc0)
  8900 mono-sgen RET   _umtx_op -1 errno 60 Operation timed out
```

Repeat ad infinitum; turns a 28 minute build into hours and essentially breaks mono-sgen for running. Obviously two separate issues, but definitely related. I think this is going to force the issue into using `CLOCK_MONOTONIC_FAST `. Other projects have observed significant improvements, and there is definitely a known precision loss risk. 

I don't believe that switching to `CLOCK_MONOTONIC_FAST` is going to fix the compiler error. But since we're going to be in here anyways, may as well get it done.

**Comment by fanyang-mono** [comment]
I am actively working on it now. Sorry for the delay.

**Comment by fanyang-mono** [comment]
@rootwyrm Is there a reproduction script that I could use to reproduce locally?

**Comment by rootwyrm** [comment]
No worries! If you have a FreeBSD box available, the quickest (and simplest) reproduction which presumes you already have bash installed:

```
#!/usr/bin/env bash
REPO="put_repo_url_here"

# Install prereqs if they're not there.
for prereq in gmake cmake libinotify zip libiconv python37; do
    pkg install -y $prereq
done

export ac_cv_header_sys_inotify_h=yes
export CC=clang
export CXX=clang++

git clone $REPO mono_freebsd
cd mono_freebsd
./autogen.sh --prefix=/usr/local --enable-maintainer-mode --enable-compile-warnings --disable-dtrace
gmake
```

**Comment by fanyang-mono** [comment]
@rootwyrm I could reproduce the error in your first comment. However, I didn't encounter any hang. It took me less than half an hour to finish the build.
