### ISSUE TITLE
Why can we not use Mono 5.18 to build Mono 5.20 but need to bootstrap again?

### ISSUE THREAD

**Issue by tpokorra** [mono/mono#15643]
For Fedora, we are happy to have upgraded to Mono 5.18 successfully, with a bootstrap.
Now I tried to work on Mono 5.20, without doing another bootstrap.

But it seems, I get the error: runtime is not usable.
BUILDSTDERR: *** Downloading bootstrap required 'monolite-linux/B886E13F-6276-4BE5-85F8-C6BF5EDBD200'
BUILDSTDERR: *** The runtime 'mono' doesn't appear to be usable.
BUILDSTDERR: *** Check README for information on how to bootstrap a Mono installation.
see https://bugzilla.redhat.com/show_bug.cgi?id=1697526

I did some debugging, and tried to tweak the build process.
I have an installed MONO_CORLIB_VERSION = 179F7FD7-9CE8-424E-84AF-0DF5B0B8B469
But even if I change that value in mcs/build/config.make, and point the monolite directory to my installed mono:
cd /root/rpmbuild/BUILD/mono-5.20.1.27/mcs/class/lib/monolite-linux
ln -s  /usr/lib/mono/4.5 179F7FD7-9CE8-424E-84AF-0DF5B0B8B469

I get these issues:
Corlib not in sync with this runtime: The runtime did not find the mscorlib.dll it expected. Expected interface version B886E13F-6276-4BE5-85F8-C6BF5EDBD200 but found 179F7FD7-9CE8-424E-84AF-0DF5B0B8B469. Check that your runtime and class libraries are matching.
Loaded from: /usr/lib/mono/4.5/mscorlib.dll

The question is: Is bootstrap required for each minor release?
If that is the case, then be it, but if there would be a way around that, I would appreciate any help! Thanks!

**Comment by tpokorra** [comment]
I did more experimenting.

It seems, it actually requires new functionality to build Mono 5.20:

```
../../../external/cecil/Mono.Cecil.Cil/Symbols.cs(23,3): error CS0647: Error during emitting `System.Runtime.InteropServices.StructLayoutAttribute' attribute. The reason is `Object reference not set to an instance of an object'
Compilation failed: 1 error(s), 0 warnings
make[7]: *** [../../build/library.make:337: ../../class/lib/basic/tmp/Mono.Cecil.dll] Error 1
make[6]: *** [../../build/rules.make:216: do-all] Error 2
make[5]: *** [../build/rules.make:237: all-recursive] Error 1
make[4]: *** [build/rules.make:237: all-recursive] Error 1
make[3]: *** [Makefile:54: profile-do--basic--all] Error 2
make[2]: *** [Makefile:50: profiles-do--all] Error 2
make[1]: *** [Makefile:629: all-mcs] Error 2
make[1]: Leaving directory '/root/rpmbuild/BUILD/mono-5.20.1.27/runtime'
make: *** [Makefile:39: dir-check] Error 2
```

**Comment by marek-safar** [comment]
Correct, we update the bootstrap requirement only when new functionality is needed to actually build.
