### ISSUE TITLE
regression building mscorlib on build-unix

### ISSUE THREAD

**Issue by NattyNarwhal** [mono/mono#11979]
When on the build-unix stage, mscorlib has dependency issues, preventing it from building? Regression caused by #11342.

## Steps to Reproduce

1.  build mono with BCL

### Current Behavior

build failure

### Expected Behavior

normal build

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[ ] Windows
[X] AIX

**Version Used**:

master

## Stacktrace

```
gmake[2]: Entering directory '/home/calvin/mono-build/mono/runtime'
if test -w /home/calvin/mono-build/mono/mcs; then :; else chmod -R +w /home/calvin/mono-build/mono/mcs; fi
cd /home/calvin/mono-build/mono/mcs && gmake --no-print-directory -s NO_DIR_CHECK=1 PROFILES='binary_reference_assemblies net_4_x xbuild_12 xbuild_14            ' CC='gcc' all-profiles
MCS     [build-unix] mscorlib.dll
error CS0518: The predefined type `System.Object' is not defined or imported
error CS0518: The predefined type `System.ValueType' is not defined or imported
error CS0518: The predefined type `System.Attribute' is not defined or imported
error CS0518: The predefined type `System.Int32' is not defined or imported
error CS0518: The predefined type `System.UInt32' is not defined or imported
error CS0518: The predefined type `System.Int64' is not defined or imported
error CS0518: The predefined type `System.UInt64' is not defined or imported
error CS0518: The predefined type `System.Single' is not defined or imported
error CS0518: The predefined type `System.Double' is not defined or imported
error CS0518: The predefined type `System.Char' is not defined or imported
error CS0518: The predefined type `System.Int16' is not defined or imported
error CS0518: The predefined type `System.Decimal' is not defined or imported
error CS0518: The predefined type `System.Boolean' is not defined or imported
error CS0518: The predefined type `System.SByte' is not defined or imported
error CS0518: The predefined type `System.Byte' is not defined or imported
error CS0518: The predefined type `System.UInt16' is not defined or imported
error CS0518: The predefined type `System.String' is not defined or imported
error CS0518: The predefined type `System.Enum' is not defined or imported
error CS0518: The predefined type `System.Delegate' is not defined or imported
error CS0518: The predefined type `System.MulticastDelegate' is not defined or imported
error CS0518: The predefined type `System.Void' is not defined or imported
error CS0518: The predefined type `System.Array' is not defined or imported
error CS0518: The predefined type `System.Type' is not defined or imported
error CS0518: The predefined type `System.Collections.IEnumerator' is not defined or imported
error CS0518: The predefined type `System.Collections.IEnumerable' is not defined or imported
error CS0518: The predefined type `System.IDisposable' is not defined or imported
error CS0518: The predefined type `System.IntPtr' is not defined or imported
error CS0518: The predefined type `System.UIntPtr' is not defined or imported
error CS0518: The predefined type `System.RuntimeFieldHandle' is not defined or imported
error CS0518: The predefined type `System.RuntimeTypeHandle' is not defined or imported
error CS0518: The predefined type `System.Exception' is not defined or imported
Compilation failed: 31 error(s), 0 warnings
../../build/library.make:329: recipe for target '../../class/lib/build-unix/mscorlib.dll' failed
gmake[8]: *** [../../class/lib/build-unix/mscorlib.dll] Error 1
../../build/rules.make:215: recipe for target 'do-all' failed
gmake[7]: *** [do-all] Error 2
../build/rules.make:236: recipe for target 'all-recursive' failed
gmake[6]: *** [all-recursive] Error 1
build/rules.make:236: recipe for target 'all-recursive' failed
gmake[5]: *** [all-recursive] Error 1
Makefile:56: recipe for target 'profile-do--build--all' failed
gmake[4]: *** [profile-do--build--all] Error 2
Makefile:52: recipe for target 'profiles-do--all' failed
gmake[3]: *** [profiles-do--all] Error 2
Makefile:638: recipe for target 'all-mcs' failed
gmake[2]: *** [all-mcs] Error 2
gmake[2]: Leaving directory '/home/calvin/mono-build/mono/runtime'
Makefile:572: recipe for target 'all-recursive' failed
gmake[1]: *** [all-recursive] Error 1
gmake[1]: Leaving directory '/home/calvin/mono-build/mono'
Makefile:502: recipe for target 'all' failed
gmake: *** [all] Error 2
```

**Comment by NattyNarwhal** [comment]
I assume these outputs don't look right, but I'm not sure why I'm getting the output (this is the gensources for corlib, but with trace 4)

https://gist.github.com/NattyNarwhal/5d19279e012ee7340bf6cc26912f7cf8

**Comment by NattyNarwhal** [comment]
Found it: linux/mac/whatever imports `corlib.dll.sources` and `unix*.sources`. Unfortunately, `unix` platforms like AIX and FreeBSD only import the `unix` sources. The `unix` sources should include common corlib files, and then the other platforms modified to do that; or something else?

cc @alexischr because I'm not certain if this is the preferred approach to the problem

**Comment by NattyNarwhal** [comment]
Oh, and to add, it looks like `net_4_x` looks fine; just `build` is problematic.

**Comment by NattyNarwhal** [comment]
I can confirm adding an import corlib.dll.sources to the top of unix build sources works; though maybe hacky.

It did expose a CoreFX portability issue, but I'll need to take that WTF with them...

**Comment by NattyNarwhal** [comment]
(for the curious, dotnet/corefx#33935 is the portaibility wtf)

**Comment by NattyNarwhal** [comment]
Alright then, I can wait; hopefully nothing big gets merged in the meantime.

**Comment by marek-safar** [comment]
@alexischr @NattyNarwhal is this issue still happening?

**Comment by NattyNarwhal** [comment]
This part is fixed, just waiting on the other bug to get fixed.
