### ISSUE TITLE
Ambiguous call Encoding.GetByteCount(char[], int, int) and Encoding.GetByteCount(string, int, int)

### ISSUE THREAD

**Issue by lambdageek** [mono/mono#8422]
Seen here https://jenkins.mono-project.com/job/test-mono-acceptancetests/960/

```
external/coreclr/tests/src/CoreMangLib/cti/system/text/unicodeencoding/unicodeencodinggetbytecount1.cs(189,37):
error CS0121: The call is ambiguous between the following methods or properties:
'Encoding.GetByteCount(char[], int, int)' and 'Encoding.GetByteCount(string, int, int)'
```

Seems to have started with https://github.com/mono/mono/pull/7948

**Comment by lambdageek** [comment]
@EgorBo Is the new public method in `System.Text.Encoding.GetByteCount(string, int, int)` really necessary? I can see it's in .NET Core, but it's not in .NET Standard or .NET Framework and wasn't in Mono.

**Comment by EgorBo** [comment]
@lambdageek there was a file in ComponentModel that needed that overload (but then it was excluded) so I guess it is not. But will be introduced with https://github.com/mono/mono/pull/7466 again

**Comment by marek-safar** [comment]
This is expected API breakage which happens in test scenarios (unexpected) only.
