### ISSUE TITLE
No longer builds with CentOS 6 (GCC 4.4.7)

### ISSUE THREAD

**Issue by directhex** [mono/mono#7408]
```
DEBUG:   CC     libmonoutils_la-os-event-unix.lo
DEBUG: In file included from ../../mono/metadata/image.h:10,
DEBUG:                  from ../../mono/metadata/metadata.h:12,
DEBUG:                  from ../../mono/metadata/class.h:8,
DEBUG:                  from ../../mono/metadata/object.h:9,
DEBUG:                  from ../../mono/metadata/appdomain.h:16,
DEBUG:                  from ../../mono/utils/mono-stack-unwinding.h:10,
DEBUG:                  from mono-threads.h:15,
DEBUG:                  from mono-lazy-init.h:19,
DEBUG:                  from os-event-unix.c:14:
DEBUG: ../../mono/utils/mono-error.h:70: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: In file included from ../../mono/metadata/metadata.h:12,
DEBUG:                  from ../../mono/metadata/class.h:8,
DEBUG:                  from ../../mono/metadata/object.h:9,
DEBUG:                  from ../../mono/metadata/appdomain.h:16,
DEBUG:                  from ../../mono/utils/mono-stack-unwinding.h:10,
DEBUG:                  from mono-threads.h:15,
DEBUG:                  from mono-lazy-init.h:19,
DEBUG:                  from os-event-unix.c:14:
DEBUG: ../../mono/metadata/image.h:58: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/image.h:60: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: In file included from ../../mono/metadata/class.h:8,
DEBUG:                  from ../../mono/metadata/object.h:9,
DEBUG:                  from ../../mono/metadata/appdomain.h:16,
DEBUG:                  from ../../mono/utils/mono-stack-unwinding.h:10,
DEBUG:                  from mono-threads.h:15,
DEBUG:                  from mono-lazy-init.h:19,
DEBUG:                  from os-event-unix.c:14:
DEBUG: ../../mono/metadata/metadata.h:240: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/metadata.h:399: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/metadata.h:406: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/metadata.h:410: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/metadata.h:415: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/metadata.h:418: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/metadata.h:437: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/metadata.h:443: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/metadata.h:452: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: In file included from ../../mono/metadata/class.h:10,
DEBUG:                  from ../../mono/metadata/object.h:9,
DEBUG:                  from ../../mono/metadata/appdomain.h:16,
DEBUG:                  from ../../mono/utils/mono-stack-unwinding.h:10,
DEBUG:                  from mono-threads.h:15,
DEBUG:                  from mono-lazy-init.h:19,
DEBUG:                  from os-event-unix.c:14:
DEBUG: ../../mono/metadata/loader.h:17: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/loader.h:21: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/loader.h:25: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/loader.h:32: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/loader.h:35: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/loader.h:41: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: In file included from ../../mono/metadata/object.h:9,
DEBUG:                  from ../../mono/metadata/appdomain.h:16,
DEBUG:                  from ../../mono/utils/mono-stack-unwinding.h:10,
DEBUG:                  from mono-threads.h:15,
DEBUG:                  from mono-lazy-init.h:19,
DEBUG:                  from os-event-unix.c:14:
DEBUG: ../../mono/metadata/class.h:23: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/class.h:27: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/class.h:34: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/class.h:37: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/class.h:40: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/class.h:47: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/class.h:54: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/class.h:57: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/class.h:61: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/class.h:65: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/class.h:69: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/class.h:73: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/class.h:77: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/class.h:81: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/class.h:131: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: In file included from ../../mono/metadata/appdomain.h:16,
DEBUG:                  from ../../mono/utils/mono-stack-unwinding.h:10,
DEBUG:                  from mono-threads.h:15,
DEBUG:                  from mono-lazy-init.h:19,
DEBUG:                  from os-event-unix.c:14:
DEBUG: ../../mono/metadata/object.h:76: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/object.h:80: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/object.h:85: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/object.h:89: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/object.h:93: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/object.h:97: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/object.h:102: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/object.h:106: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/object.h:110: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/object.h:123: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/object.h:127: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/object.h:131: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/object.h:135: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/object.h:142: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/object.h:146: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/object.h:153: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/object.h:157: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/object.h:161: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/object.h:174: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/object.h:178: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/object.h:191: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/object.h:195: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/object.h:217: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/object.h:221: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/object.h:225: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/object.h:229: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/object.h:248: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/object.h:252: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/object.h:256: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/object.h:260: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/object.h:274: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/object.h:288: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/object.h:293: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/object.h:297: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/object.h:301: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/object.h:311: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/object.h:316: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/object.h:325: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/object.h:329: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/object.h:333: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/object.h:337: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/object.h:349: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/object.h:363: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/object.h:367: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/object.h:371: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/object.h:375: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: In file included from ../../mono/metadata/appdomain.h:17,
DEBUG:                  from ../../mono/utils/mono-stack-unwinding.h:10,
DEBUG:                  from mono-threads.h:15,
DEBUG:                  from mono-lazy-init.h:19,
DEBUG:                  from os-event-unix.c:14:
DEBUG: ../../mono/metadata/reflection.h:50: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/reflection.h:52: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: In file included from ../../mono/metadata/appdomain.h:17,
DEBUG:                  from ../../mono/utils/mono-stack-unwinding.h:10,
DEBUG:                  from mono-threads.h:15,
DEBUG:                  from mono-lazy-init.h:19,
DEBUG:                  from os-event-unix.c:14:
DEBUG: ../../mono/metadata/reflection.h:55: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/reflection.h:57: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/reflection.h:60: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/reflection.h:62: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/reflection.h:64: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/reflection.h:67: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/reflection.h:69: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/reflection.h:71: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/reflection.h:73: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/reflection.h:76: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/reflection.h:78: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/reflection.h:85: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/reflection.h:87: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/reflection.h:90: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/reflection.h:92: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/reflection.h:94: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/reflection.h:96: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/reflection.h:98: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/reflection.h:100: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/reflection.h:102: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/reflection.h:104: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/reflection.h:106: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/reflection.h:108: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/reflection.h:111: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: In file included from ../../mono/utils/mono-stack-unwinding.h:10,
DEBUG:                  from mono-threads.h:15,
DEBUG:                  from mono-lazy-init.h:19,
DEBUG:                  from os-event-unix.c:14:
DEBUG: ../../mono/metadata/appdomain.h:45: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/appdomain.h:70: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/appdomain.h:74: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/appdomain.h:96: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/appdomain.h:106: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/appdomain.h:125: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/appdomain.h:132: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: ../../mono/metadata/appdomain.h:136: error: wrong number of arguments specified for '__deprecated__' attribute
DEBUG: make[5]: Leaving directory `/builddir/build/BUILD/mono-5.13.0.308/mono/utils'
DEBUG: make[4]: Leaving directory `/builddir/build/BUILD/mono-5.13.0.308/mono/utils'
DEBUG: make[3]: Leaving directory `/builddir/build/BUILD/mono-5.13.0.308/mono/utils'
DEBUG: make[2]: Leaving directory `/builddir/build/BUILD/mono-5.13.0.308/mono'
DEBUG: make[1]: Leaving directory `/builddir/build/BUILD/mono-5.13.0.308'
DEBUG: RPM build errors:
DEBUG: make[5]: *** [libmonoutils_la-os-event-unix.lo] Error 1
DEBUG: make[4]: *** [all-recursive] Error 1
DEBUG: make[3]: *** [all] Error 2
DEBUG: make[2]: *** [all-recursive] Error 1
DEBUG: make[1]: *** [all-recursive] Error 1
DEBUG: make: *** [all] Error 2
```

**Comment by akoeplinger** [comment]
We need to check for GCC >= 4.5: https://github.com/lz4/lz4/issues/272

**Comment by marek-safar** [comment]
@jaykrell could you take care of this?

**Comment by jaykrell** [comment]
Fair enough, yes. I should have seen that coming.

**Comment by akoeplinger** [comment]
Fixed with https://github.com/mono/mono/pull/7419
