### ISSUE TITLE
C# REPL Unusable on Mono 6 / Ubuntu 19

### ISSUE THREAD

**Issue by nkosi23** [mono/mono#16701]
## Steps to Reproduce

1. Launch the REPL with the "csharp" command on Ubuntu 19 / Mono 6.0.0.327
2. Type any C# statement in the REPL

### Current Behavior

The cursor isn't are right place, it is always at the top of screen therefore the text and the output of statements always overlap with the previously written text, making the shell unusable in practice.

![2019-09-06_10-34-46](https://user-images.githubusercontent.com/6731436/64413647-2a994080-d092-11e9-8a24-713ee607a29f.png)
![2019-09-06_10-35-21](https://user-images.githubusercontent.com/6731436/64413657-2ec55e00-d092-11e9-95be-9ed731facd3b.png)

![2019-09-06_10-26-03](https://user-images.githubusercontent.com/6731436/64413396-b9598d80-d091-11e9-9d40-1d865a0847ba.png)
![2019-09-06_10-30-04](https://user-images.githubusercontent.com/6731436/64413407-bd85ab00-d091-11e9-89b1-fa758d678652.png)
![2019-09-06_10-31-27](https://user-images.githubusercontent.com/6731436/64413419-c1193200-d091-11e9-87db-00e201358023.png)
![2019-09-06_10-32-22](https://user-images.githubusercontent.com/6731436/64413434-c4142280-d091-11e9-90a1-332b3cdade8c.png)

### Expected Behavior

The output and cursor should be on the last line of the screen

## On which platforms did you notice this

[ ] macOS
[ X] Linux
[ ] Windows

**Version Used**:

Mono 6.0.0.327. Reproduced on both the xcfe terminal and the xterm terminal (only two terminals I have installed), so the problem comes from the C# REPL and not from the terminal.

**Comment by lewurm** [comment]
does `$TERM` match with the terminal you are using?

**Comment by Therzok** [comment]
@lwurm i've seen this on macos too

**Comment by nkosi23** [comment]
@lewurm What do you mean? Typing $TERM in the REPL throws an error

>Error CS1056: Unexpected Character '$'

By removing the '$' I get an error CS0103 "The name TERM does not exist in the current context.

**Comment by lewurm** [comment]
huch... I couldn't reproduce it at first:
* running it from a `screen(1)` session + iTerm2 + `TERM=rxvt` works _fine_.
* running from a plain iTerm2 session + `TERM=rxvt` behaves like reported.

I'll poke around a bit. I'm a afraid that it's caused by https://github.com/mono/mono/pull/6960 as this function is called everytime the prompt is printed:
https://github.com/mono/mono/blob/1f76ab9270db6db36481bbfde99a7e90256b70f9/mcs/tools/csharp/getline.cs#L291-L298
... and that queries the terminal for `CursorTop`.

**Comment by lewurm** [comment]
> @lewurm What do you mean? Typing $TERM in the REPL throws an error
> 
> > Error CS1056: Unexpected Character '$'
> 
> By removing the '$' I get an error CS0103 "The name TERM does not exist in the current context.

not in `csharp`, but in your regular shell:
```console
$ echo $TERM
xterm
```

I poked a bit at it, but I'm not sure about the fix: https://github.com/mono/mono/pull/16745
