### PR TITLE
Fix compilation errors in mono/utils/os-event-win32.c with Mingw/GCC

### PR DESCRIPTION
**Pull request by ntherning**
This was introduced in 92be5357d12ecf0cc4c51fbcb76fc0514b375d1c. The patch also adds the os-event-win32.c file to the libmonoutils Visual Studio project.

### CODE REVIEW

**Comment by ntherning** [comment]
@ludovic-henry Please review this and merge if it looks ok.
